print('Calculadora de aumento de salário')
s1 = float(input('Valor do salário: R$ '))
a1 = float(input('Valor do aumento (porcentagem): '))
sf = s1 + (s1 * a1/100)
print('Seu novo salário, com um aumento de {}%, é igual a: {}'.format(a1,sf))
